### ISSUE TITLE
TM-Recharge issue

### ISSUE THREAD

**Issue by saeedmhanna1** [guiattard/geoscience-notebooks#3]
Dear Mr. Attard, 

While going throught the [tutorial](https://developers.google.com/earth-engine/tutorials/community/groundwater-recharge-estimation#implementation_of_the_tm_procedure): "Implementation of the Thornthwaite-Mather procedure to map groundwater recharge", I noticed a few things:

There is an error with the of APWL equation in case 2.2,  where it is missing a negative sign (the description not the code). Otherwise ln will return a negative number. 

More importantly, I believe that there is an error when APWL is calculated. I tried doing the calculation manually using the equation described in the reference paper and got completely different values of recharge. 

In the table showing APWL, p, pet, rech and st for 2015 for example, apwl rises from 0 to 527mm in march 2015, which makes absolutely no sense physically.  Even when changing the scale to 500 (the original resolution of MODIS), the problem persists. 

We can see the error clearly in the first year, we plot apwl against pet and pr in the charts.

Any feedback on that issue? 

Thanks, 
Saeed

**Comment by saeedmhanna1** [comment]
![image](https://github.com/guiattard/geoscience-notebooks/assets/145265098/15dd3f00-6fbf-4ae2-b6ab-96ab5cc2abd1)

**Comment by saeedmhanna1** [comment]
![image](https://github.com/guiattard/geoscience-notebooks/assets/145265098/403dce2e-e8fd-4ad1-ab10-4f89163351d3)

**Comment by guiattard** [comment]
Dear Saeed,

Thanks for your message and for noticing an issue. I'll try to have a look.

**Comment by guiattard** [comment]
Dear Saeed,

After some investigation, I think the issue comes from the fact that the resampled meteorological collection is not well sorted (from the older image to the most recent).  

Please try to sort the collection and tell me if it's okay for you:

`
# Combine precipitation and evapotranspiration.
meteo = pr_m.combine(pet_m).sort("system:time_start")
`

**Comment by Wilfried-DJOMATCHOUA** [comment]
Dear Mr. Attard, 

While working with Saeed on my MSc project, I realized that there was another issue in the code. 

The St in the recharge calculator function (line 1384) is prev.st. However it should be STfc in accordance with the reference Steenhuis and Van der Molen (1985). 

Other than that, the code works well when sorting the meteo ImageCollection. 

Thanks, 
Wilfried DATCHOUA.

**Comment by guiattard** [comment]
Dear Wilfried,

Thanks for noticing. Indeed you are right about the error line 1384.

Do you have any other comment before I send the request to edit the tutorial to the product team?

Thanks,

**Comment by guiattard** [comment]
Hi,

The tutorial has been updated regarding your comments: https://developers.google.com/earth-engine/tutorials/community/groundwater-recharge-estimation

Thanks for your contribution.

**Comment by Wilfried-DJOMATCHOUA** [comment]
Hello,
I've looked at your new code, and it seems to work perfectly.
However, I was able to locate two errors that may be of interest to you. 
When I ran your code on shorter time steps (daily with a new function that transforms pentad data into days):
- the PET satellite data you use (ee.ImageCollection("MODIS/006/MOD16A2")) show many days where there is no data. (Proof analysis of excel documents at different points over a period of one year)
- There is an error in your script: the formula for calculating the recharge given in the description (𝑅𝑚=𝑆𝑇𝑚-𝑆𝑇𝐹𝐶+𝑃𝑚-𝑃𝐸𝑇𝑚) does not correspond to the one used in the code and the one described in the publication by the author of the method (Steenhuis and Van der Molen (1985)).

Therefore, I suggest replacing :
- 𝑅𝑚=𝑆𝑇𝑚-𝑆𝑇𝐹𝐶+𝑃𝑚-𝑃𝐸𝑇𝑚 by 𝑅𝑚=(𝑆𝑇𝑚-1)-𝑆𝑇𝐹𝐶+𝑃𝑚-𝑃𝐸𝑇𝑚 or by 𝑅𝑚=𝑆𝑇𝑚-𝑆𝑇𝐹𝐶 as you have done in the code that calculates the reload.
- ee.ImageCollection("MODIS/006/MOD16A2") by ee.ImageCollection("MODIS/061/MOD16A2GF") which has the same spatial resolution as the previous one but with the advantage of having less missing data.

Yours sincerely, Wilfried  DATCHOUA
